CREATE TABLE IF NOT EXISTS feedback
(
    ID       BIGSERIAL       NOT NULL,
    TIME     VARCHAR(50)  NOT NULL,
    MOVIE_ID   INTEGER      NOT NULL,
    USER_ID   INTEGER      NOT NULL,
    NAME     VARCHAR(100) NOT NULL,
    FEEDBACK VARCHAR(500) NOT NULL,
    SCORE INTEGER NOT NULL
)
