CREATE TABLE IF NOT EXISTS event
(
    ID       BIGSERIAL       NOT NULL,
    TIME     VARCHAR(100)  NOT NULL UNIQUE,
    MOVIE_ID   INTEGER      NOT NULL,
    HALL_ID   INTEGER      NOT NULL,
    FREE_PLACES     INTEGER NOT NULL,
    PLACE_COST INTEGER NOT NULL
    )
