CREATE TABLE IF NOT EXISTS users
(
    ID             BIGSERIAL      NOT NULL,
    LOGIN         VARCHAR (100)     NOT NULL UNIQUE,
    PASSWORD     VARCHAR(100)  NOT NULL,
    ROLE        VARCHAR (50)     NOT NULL,
    FIRST_NAME     VARCHAR(100) NOT NULL,
    SECOND_NAME VARCHAR(100)   NOT NULL,
    GENDER           VARCHAR(50)  NOT NULL,
    BIRTHDAY_DATE      VARCHAR(100) NOT NULL
    )
