CREATE TABLE IF NOT EXISTS movie
(
    ID          SERIAL       NOT NULL,
    TITLE       VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    RELEASE     VARCHAR(10)  NOT NULL,
    GENRE       VARCHAR(50)  NOT NULL,
    PRODUCTION  VARCHAR(20)  NOT NULL,
    ACTORS      VARCHAR(200) NOT NULL,
    IMAGE  BYTEA,
    TRAILER VARCHAR (100),
    RATING INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS feedback
(
    ID       BIGSERIAL       NOT NULL,
    TIME     VARCHAR(50)  NOT NULL,
    MOVIE_ID   INTEGER      NOT NULL,
    USER_ID   INTEGER      NOT NULL,
    NAME     VARCHAR(100) NOT NULL,
    FEEDBACK VARCHAR(500) NOT NULL,
    SCORE INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS hall
(
    ID   SERIAL     NOT NULL,
    NAME     VARCHAR(100) NOT NULL UNIQUE,
    PLACES INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS event
(
    ID       BIGSERIAL       NOT NULL,
    TIME     VARCHAR(100)  NOT NULL UNIQUE,
    MOVIE_ID   INTEGER      NOT NULL,
    HALL_ID   INTEGER      NOT NULL,
    FREE_PLACES     INTEGER NOT NULL,
    PLACE_COST INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS ticket
(
    ID             BIGSERIAL       NOT NULL,
    OWNER          VARCHAR(50)  NOT NULL,
    USER_ID        BIGSERIAL      NOT NULL,
    MOVIE_NAME     VARCHAR(100) NOT NULL,
    PLACE_QUANTITY INTEGER      NOT NULL,
    TIME           VARCHAR(100)  NOT NULL,
    HALL_NAME      VARCHAR(100) NOT NULL,
    EVENT_ID       BIGSERIAL      NOT NULL,
    COMMON_AMOUNT INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS users
(
    ID             BIGSERIAL      NOT NULL,
    LOGIN         VARCHAR (100)     NOT NULL UNIQUE,
    PASSWORD     VARCHAR(100)  NOT NULL,
    ROLE        VARCHAR (50)     NOT NULL,
    FIRST_NAME     VARCHAR(100) NOT NULL,
    SECOND_NAME VARCHAR(100)   NOT NULL,
    GENDER           VARCHAR(50)  NOT NULL,
    BIRTHDAY_DATE      VARCHAR(100) NOT NULL
    );
